# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2023-02-24 12:49
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields
import osf.models.base


class Migration(migrations.Migration):

    dependencies = [
        ('addons_osfstorage', '0006_rename_deleted_field'),
        ('osf', '0224_ensure_schema_and_reports'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserStorageQuota',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('max_quota', models.IntegerField(default=0)),
                ('used', models.BigIntegerField(default=0)),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='addons_osfstorage.Region')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            bases=(models.Model, osf.models.base.QuerySetExplainMixin),
        ),
        migrations.AlterUniqueTogether(
            name='userstoragequota',
            unique_together=set([('user', 'region')]),
        ),
    ]
