# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2023-03-23 09:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import osf.models.base
import osf.utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('osf', '0225_auto_20230224_1249'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuthenticationAttribute',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index_number', models.IntegerField()),
                ('attribute_name', models.CharField(blank=True, max_length=255, null=True)),
                ('attribute_value', models.CharField(blank=True, max_length=255, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted', osf.utils.fields.NonNaiveDateTimeField(blank=True, null=True)),
                ('created', osf.utils.fields.NonNaiveDateTimeField(auto_now_add=True)),
                ('modified', osf.utils.fields.NonNaiveDateTimeField(auto_now=True, null=True)),
            ],
            bases=(models.Model, osf.models.base.QuerySetExplainMixin),
        ),
        migrations.AddField(
            model_name='institution',
            name='is_authentication_attribute',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='authenticationattribute',
            name='institution',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='osf.Institution'),
        ),
        migrations.AlterUniqueTogether(
            name='authenticationattribute',
            unique_together=set([('institution', 'index_number')]),
        ),
    ]
