# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2022-08-23 09:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addons_osfstorage', '0006_rename_deleted_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='region',
            name='is_allowed',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='region',
            name='is_primary',
            field=models.BooleanField(default=False),
        ),
    ]
