# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2023-03-23 09:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addons_osfstorage', '0007_auto_20230213_1117'),
    ]

    operations = [
        migrations.AddField(
            model_name='region',
            name='allow_expression',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='region',
            name='readonly_expression',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
